# Generated by Django 5.0.2 on 2024-02-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_discount_tax_item_currency_item_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='stripe_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
